markdown: kramdown

defaults:
  - scope:
      path: "" # empty string for all files
    values:
      layout: default
      
navigation:
  - text: Home
    url: /
    children: false
  - text: About
    url: /about.html
    children: false
#  - text: Portfolio
#    url: /portfolio.html
  - text: Careers Info
    url: ~
    children:
      - text: Achievements
        url: /careersinfo/achievements.html
      - text: Career Talks
        url: /careersinfo/careertalks.html
      - text: Self Evaluation
        url: /careersinfo/selfevaluation.html
      - text: Tertiary Options
        url: /careersinfo/tertiary.html