gems:
  - jekyll-redirect-from
defaults:
  - scope:
      path: "" # empty string for all files
    values:
      layout: "default"
navigation:
  - text: Home
    url: /eportfolio/
  - text: About
    url: /eportfolio/about.html
  - text: Portfolio
    url: /eportfolio/portfolio.html
  - text: Careers Info
    url: ~
    children:
      - text: Achievements
        url: /eportfolio/careersinfo/achievements.html
      - text: Career Talks
        url: /eportfolio/careersinfo/careertalks.html
      - text: Self Evaluation
        url: /eportfolio/careersinfo/selfevaluation.html
      - text: Tertiary Options
        url: /eportfolio/careersinfo/tertiary.html